import * as k8s from "@pulumi/kubernetes";
import * as pulumi from "@pulumi/pulumi";

import type { SecretRef } from "./secret-ref.ts";

const PSQL_IMAGE = "postgres:16-alpine";

export type PostgresRole = {
  // Service-owned schema name (also used as the database role's display name —
  // role becomes `<schema>_user` per ADR-0003 and `infra/docker/postgres-init.sql`).
  schema: string;
  password: SecretRef;
};

export type PostgresRolesArgs = {
  namespace: pulumi.Input<string>;
  postgresHost: pulumi.Input<string>;
  postgresPort: number;
  database: string;
  adminUser: string;
  adminPassword: SecretRef;
  roles: PostgresRole[];
};

// Bootstraps per-service Postgres roles + schemas (ADR-0003) idempotently on
// every `pulumi up`. Mirrors `infra/docker/postgres-init.sql` so the kind stack
// matches the compose stack.
export class PostgresRoles extends pulumi.ComponentResource {
  readonly configMap: k8s.core.v1.ConfigMap;
  readonly job: k8s.batch.v1.Job;

  constructor(name: string, args: PostgresRolesArgs, opts?: pulumi.ComponentResourceOptions) {
    super("tix:infra:PostgresRoles", name, args, opts);

    const childOpts: pulumi.ResourceOptions = { parent: this };
    const sql = renderBootstrapSql(args.roles, args.database);

    this.configMap = new k8s.core.v1.ConfigMap(
      `${name}-sql`,
      {
        metadata: { name: `${name}-sql`, namespace: args.namespace },
        data: { "bootstrap.sql": sql },
      },
      childOpts,
    );

    const roleEnv: k8s.types.input.core.v1.EnvVar[] = args.roles.map((role) => ({
      name: `${role.schema.toUpperCase()}_PASSWORD`,
      valueFrom: { secretKeyRef: { name: role.password.name, key: role.password.key } },
    }));

    this.job = new k8s.batch.v1.Job(
      `${name}-job`,
      {
        metadata: { name, namespace: args.namespace },
        spec: {
          backoffLimit: 5,
          ttlSecondsAfterFinished: 600,
          template: {
            metadata: {
              labels: {
                "app.kubernetes.io/name": name,
                "app.kubernetes.io/component": "bootstrap",
              },
            },
            spec: {
              restartPolicy: "OnFailure",
              containers: [
                {
                  name: "psql",
                  image: PSQL_IMAGE,
                  command: ["sh", "-c", PSQL_ENTRYPOINT],
                  env: [
                    { name: "PGHOST", value: args.postgresHost },
                    { name: "PGPORT", value: String(args.postgresPort) },
                    { name: "PGUSER", value: args.adminUser },
                    { name: "PGDATABASE", value: args.database },
                    {
                      name: "PGPASSWORD",
                      valueFrom: {
                        secretKeyRef: {
                          name: args.adminPassword.name,
                          key: args.adminPassword.key,
                        },
                      },
                    },
                    ...roleEnv,
                  ],
                  volumeMounts: [{ name: "sql", mountPath: "/sql" }],
                },
              ],
              volumes: [
                {
                  name: "sql",
                  configMap: { name: this.configMap.metadata.name },
                },
              ],
            },
          },
        },
      },
      childOpts,
    );

    this.registerOutputs({ configMap: this.configMap, job: this.job });
  }
}

const PSQL_ENTRYPOINT = `set -eu
i=0
until pg_isready -h "$PGHOST" -p "$PGPORT" -U "$PGUSER" -d "$PGDATABASE" >/dev/null 2>&1; do
  i=$((i + 1))
  if [ "$i" -ge 60 ]; then
    echo "postgres-roles: postgres not ready after 60s" >&2
    exit 1
  fi
  sleep 1
done
exec psql -v ON_ERROR_STOP=1 -f /sql/bootstrap.sql
`;

function renderBootstrapSql(roles: PostgresRole[], database: string): string {
  const blocks = roles.map((role) => roleBlock(role.schema, database));
  return `-- Generated by tix:infra:PostgresRoles. Idempotent.\n${blocks.join("\n")}`;
}

// Idempotent role + schema bootstrap. plpgsql can't run CREATE ROLE directly
// (it's not in the prepareable-statement set), so use psql's \if/\gset instead
// of a DO block — cleaner than wrapping CREATE ROLE in EXECUTE with literal
// quoting. ALTER ROLE is unconditional so password rotation just works.
function roleBlock(schema: string, database: string): string {
  const role = `${schema}_user`;
  const envVar = `${schema.toUpperCase()}_PASSWORD`;
  const passwordVar = `${schema}_password`;
  const missingVar = `${schema}_missing`;

  return `
\\getenv ${passwordVar} ${envVar}
SELECT NOT EXISTS(SELECT 1 FROM pg_roles WHERE rolname = '${role}') AS ${missingVar} \\gset
\\if :${missingVar}
CREATE ROLE ${role} WITH LOGIN PASSWORD :'${passwordVar}';
\\endif
ALTER ROLE ${role} WITH LOGIN PASSWORD :'${passwordVar}';
ALTER ROLE ${role} SET search_path TO ${schema}, public;

CREATE SCHEMA IF NOT EXISTS ${schema} AUTHORIZATION ${role};
GRANT CREATE ON DATABASE ${database} TO ${role};
`;
}
