import * as k8s from "@pulumi/kubernetes";
import * as pulumi from "@pulumi/pulumi";

// Matches the nats-init sidecar in docker-compose.yml so the kind stack and the
// compose stack create identical streams.
const NATS_BOX_IMAGE = "natsio/nats-box:0.18.0";

export type JetStream = {
  // Stream name (e.g. `TICKETS`) and the subject wildcard it captures
  // (e.g. `tickets.>`).
  name: string;
  subjects: string;
};

export type StreamBootstrapArgs = {
  namespace: pulumi.Input<string>;
  natsUrl: pulumi.Input<string>;
  streams: JetStream[];
};

// Creates the JetStream streams idempotently on every `pulumi up`. Mirrors
// `infra/docker/nats-init.sh` so the kind stack matches the compose stack. The
// messaging consumers (`consumer` -> `ensureConsumer`) assume their stream
// already exists and crash with `StreamNotFoundError` otherwise, so every
// messaging service must `dependsOn` this Job.
export class StreamBootstrap extends pulumi.ComponentResource {
  readonly configMap: k8s.core.v1.ConfigMap;
  readonly job: k8s.batch.v1.Job;

  constructor(name: string, args: StreamBootstrapArgs, opts?: pulumi.ComponentResourceOptions) {
    super("tix:infra:StreamBootstrap", name, args, opts);

    const childOpts: pulumi.ResourceOptions = { parent: this };

    this.configMap = new k8s.core.v1.ConfigMap(
      `${name}-script`,
      {
        metadata: { name: `${name}-script`, namespace: args.namespace },
        data: { "nats-init.sh": renderInitScript(args.streams) },
      },
      childOpts,
    );

    this.job = new k8s.batch.v1.Job(
      `${name}-job`,
      {
        metadata: { name, namespace: args.namespace },
        spec: {
          backoffLimit: 5,
          ttlSecondsAfterFinished: 600,
          template: {
            metadata: {
              labels: {
                "app.kubernetes.io/name": name,
                "app.kubernetes.io/component": "bootstrap",
              },
            },
            spec: {
              restartPolicy: "OnFailure",
              containers: [
                {
                  name: "nats-init",
                  image: NATS_BOX_IMAGE,
                  command: ["sh", "/script/nats-init.sh"],
                  env: [{ name: "NATS_URL", value: args.natsUrl }],
                  volumeMounts: [{ name: "script", mountPath: "/script" }],
                },
              ],
              volumes: [{ name: "script", configMap: { name: this.configMap.metadata.name } }],
            },
          },
        },
      },
      childOpts,
    );

    this.registerOutputs({ configMap: this.configMap, job: this.job });
  }
}

// Generated stream-create script. Kept byte-for-byte aligned with the
// `ensure_stream` flags in `infra/docker/nats-init.sh` (file storage, limits
// retention, 2m dupe window) so streams have identical config in both stacks.
function renderInitScript(streams: JetStream[]): string {
  const ensures = streams.map((s) => `ensure_stream ${s.name} '${s.subjects}'`).join("\n");

  return `#!/bin/sh
# Generated by tix:infra:StreamBootstrap. Idempotent. Mirrors infra/docker/nats-init.sh.
set -eu

: "\${NATS_URL:=nats://nats:4222}"

# Wait until NATS answers an rtt probe before issuing stream commands.
i=0
until nats --server="$NATS_URL" rtt >/dev/null 2>&1; do
  i=$((i + 1))
  if [ "$i" -ge 30 ]; then
    echo "stream-bootstrap: NATS not reachable at $NATS_URL after 30s" >&2
    exit 1
  fi
  sleep 1
done

ensure_stream() {
  name="$1"
  subjects="$2"

  if nats --server="$NATS_URL" stream info "$name" >/dev/null 2>&1; then
    echo "stream-bootstrap: stream $name already exists"
    return
  fi

  nats --server="$NATS_URL" stream add "$name" \\
    --subjects "$subjects" \\
    --storage file \\
    --retention limits \\
    --discard old \\
    --max-msgs=-1 --max-bytes=-1 --max-age=24h --max-msg-size=-1 \\
    --dupe-window=2m \\
    --replicas=1 \\
    --no-allow-rollup --no-deny-delete --no-deny-purge \\
    --defaults
}

${ensures}

echo "stream-bootstrap: ok"
`;
}
