/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UiRouteImport } from './routes/ui'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TicketsIndexRouteImport } from './routes/tickets/index'
import { Route as OrdersIndexRouteImport } from './routes/orders/index'
import { Route as TicketsNewRouteImport } from './routes/tickets/new'
import { Route as TicketsMineRouteImport } from './routes/tickets/mine'
import { Route as TicketsTicketIdRouteImport } from './routes/tickets/$ticketId'
import { Route as OrdersOrderIdRouteImport } from './routes/orders/$orderId'
import { Route as AuthSignupRouteImport } from './routes/auth/signup'
import { Route as AuthSignoutRouteImport } from './routes/auth/signout'
import { Route as AuthSigninRouteImport } from './routes/auth/signin'
import { Route as TicketsTicketIdIndexRouteImport } from './routes/tickets/$ticketId.index'
import { Route as TicketsTicketIdEditRouteImport } from './routes/tickets/$ticketId.edit'

const UiRoute = UiRouteImport.update({
  id: '/ui',
  path: '/ui',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TicketsIndexRoute = TicketsIndexRouteImport.update({
  id: '/tickets/',
  path: '/tickets/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersIndexRoute = OrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => rootRouteImport,
} as any)
const TicketsNewRoute = TicketsNewRouteImport.update({
  id: '/tickets/new',
  path: '/tickets/new',
  getParentRoute: () => rootRouteImport,
} as any)
const TicketsMineRoute = TicketsMineRouteImport.update({
  id: '/tickets/mine',
  path: '/tickets/mine',
  getParentRoute: () => rootRouteImport,
} as any)
const TicketsTicketIdRoute = TicketsTicketIdRouteImport.update({
  id: '/tickets/$ticketId',
  path: '/tickets/$ticketId',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersOrderIdRoute = OrdersOrderIdRouteImport.update({
  id: '/orders/$orderId',
  path: '/orders/$orderId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/auth/signup',
  path: '/auth/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignoutRoute = AuthSignoutRouteImport.update({
  id: '/auth/signout',
  path: '/auth/signout',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSigninRoute = AuthSigninRouteImport.update({
  id: '/auth/signin',
  path: '/auth/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const TicketsTicketIdIndexRoute = TicketsTicketIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TicketsTicketIdRoute,
} as any)
const TicketsTicketIdEditRoute = TicketsTicketIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => TicketsTicketIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ui': typeof UiRoute
  '/auth/signin': typeof AuthSigninRoute
  '/auth/signout': typeof AuthSignoutRoute
  '/auth/signup': typeof AuthSignupRoute
  '/orders/$orderId': typeof OrdersOrderIdRoute
  '/tickets/$ticketId': typeof TicketsTicketIdRouteWithChildren
  '/tickets/mine': typeof TicketsMineRoute
  '/tickets/new': typeof TicketsNewRoute
  '/orders/': typeof OrdersIndexRoute
  '/tickets/': typeof TicketsIndexRoute
  '/tickets/$ticketId/edit': typeof TicketsTicketIdEditRoute
  '/tickets/$ticketId/': typeof TicketsTicketIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ui': typeof UiRoute
  '/auth/signin': typeof AuthSigninRoute
  '/auth/signout': typeof AuthSignoutRoute
  '/auth/signup': typeof AuthSignupRoute
  '/orders/$orderId': typeof OrdersOrderIdRoute
  '/tickets/mine': typeof TicketsMineRoute
  '/tickets/new': typeof TicketsNewRoute
  '/orders': typeof OrdersIndexRoute
  '/tickets': typeof TicketsIndexRoute
  '/tickets/$ticketId/edit': typeof TicketsTicketIdEditRoute
  '/tickets/$ticketId': typeof TicketsTicketIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ui': typeof UiRoute
  '/auth/signin': typeof AuthSigninRoute
  '/auth/signout': typeof AuthSignoutRoute
  '/auth/signup': typeof AuthSignupRoute
  '/orders/$orderId': typeof OrdersOrderIdRoute
  '/tickets/$ticketId': typeof TicketsTicketIdRouteWithChildren
  '/tickets/mine': typeof TicketsMineRoute
  '/tickets/new': typeof TicketsNewRoute
  '/orders/': typeof OrdersIndexRoute
  '/tickets/': typeof TicketsIndexRoute
  '/tickets/$ticketId/edit': typeof TicketsTicketIdEditRoute
  '/tickets/$ticketId/': typeof TicketsTicketIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ui'
    | '/auth/signin'
    | '/auth/signout'
    | '/auth/signup'
    | '/orders/$orderId'
    | '/tickets/$ticketId'
    | '/tickets/mine'
    | '/tickets/new'
    | '/orders/'
    | '/tickets/'
    | '/tickets/$ticketId/edit'
    | '/tickets/$ticketId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ui'
    | '/auth/signin'
    | '/auth/signout'
    | '/auth/signup'
    | '/orders/$orderId'
    | '/tickets/mine'
    | '/tickets/new'
    | '/orders'
    | '/tickets'
    | '/tickets/$ticketId/edit'
    | '/tickets/$ticketId'
  id:
    | '__root__'
    | '/'
    | '/ui'
    | '/auth/signin'
    | '/auth/signout'
    | '/auth/signup'
    | '/orders/$orderId'
    | '/tickets/$ticketId'
    | '/tickets/mine'
    | '/tickets/new'
    | '/orders/'
    | '/tickets/'
    | '/tickets/$ticketId/edit'
    | '/tickets/$ticketId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  UiRoute: typeof UiRoute
  AuthSigninRoute: typeof AuthSigninRoute
  AuthSignoutRoute: typeof AuthSignoutRoute
  AuthSignupRoute: typeof AuthSignupRoute
  OrdersOrderIdRoute: typeof OrdersOrderIdRoute
  TicketsTicketIdRoute: typeof TicketsTicketIdRouteWithChildren
  TicketsMineRoute: typeof TicketsMineRoute
  TicketsNewRoute: typeof TicketsNewRoute
  OrdersIndexRoute: typeof OrdersIndexRoute
  TicketsIndexRoute: typeof TicketsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/ui': {
      id: '/ui'
      path: '/ui'
      fullPath: '/ui'
      preLoaderRoute: typeof UiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tickets/': {
      id: '/tickets/'
      path: '/tickets'
      fullPath: '/tickets/'
      preLoaderRoute: typeof TicketsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/': {
      id: '/orders/'
      path: '/orders'
      fullPath: '/orders/'
      preLoaderRoute: typeof OrdersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tickets/new': {
      id: '/tickets/new'
      path: '/tickets/new'
      fullPath: '/tickets/new'
      preLoaderRoute: typeof TicketsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tickets/mine': {
      id: '/tickets/mine'
      path: '/tickets/mine'
      fullPath: '/tickets/mine'
      preLoaderRoute: typeof TicketsMineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tickets/$ticketId': {
      id: '/tickets/$ticketId'
      path: '/tickets/$ticketId'
      fullPath: '/tickets/$ticketId'
      preLoaderRoute: typeof TicketsTicketIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/$orderId': {
      id: '/orders/$orderId'
      path: '/orders/$orderId'
      fullPath: '/orders/$orderId'
      preLoaderRoute: typeof OrdersOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/signup': {
      id: '/auth/signup'
      path: '/auth/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/signout': {
      id: '/auth/signout'
      path: '/auth/signout'
      fullPath: '/auth/signout'
      preLoaderRoute: typeof AuthSignoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/signin': {
      id: '/auth/signin'
      path: '/auth/signin'
      fullPath: '/auth/signin'
      preLoaderRoute: typeof AuthSigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tickets/$ticketId/': {
      id: '/tickets/$ticketId/'
      path: '/'
      fullPath: '/tickets/$ticketId/'
      preLoaderRoute: typeof TicketsTicketIdIndexRouteImport
      parentRoute: typeof TicketsTicketIdRoute
    }
    '/tickets/$ticketId/edit': {
      id: '/tickets/$ticketId/edit'
      path: '/edit'
      fullPath: '/tickets/$ticketId/edit'
      preLoaderRoute: typeof TicketsTicketIdEditRouteImport
      parentRoute: typeof TicketsTicketIdRoute
    }
  }
}

interface TicketsTicketIdRouteChildren {
  TicketsTicketIdEditRoute: typeof TicketsTicketIdEditRoute
  TicketsTicketIdIndexRoute: typeof TicketsTicketIdIndexRoute
}

const TicketsTicketIdRouteChildren: TicketsTicketIdRouteChildren = {
  TicketsTicketIdEditRoute: TicketsTicketIdEditRoute,
  TicketsTicketIdIndexRoute: TicketsTicketIdIndexRoute,
}

const TicketsTicketIdRouteWithChildren = TicketsTicketIdRoute._addFileChildren(
  TicketsTicketIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  UiRoute: UiRoute,
  AuthSigninRoute: AuthSigninRoute,
  AuthSignoutRoute: AuthSignoutRoute,
  AuthSignupRoute: AuthSignupRoute,
  OrdersOrderIdRoute: OrdersOrderIdRoute,
  TicketsTicketIdRoute: TicketsTicketIdRouteWithChildren,
  TicketsMineRoute: TicketsMineRoute,
  TicketsNewRoute: TicketsNewRoute,
  OrdersIndexRoute: OrdersIndexRoute,
  TicketsIndexRoute: TicketsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
