import * as k8s from "@pulumi/kubernetes";
import * as pulumi from "@pulumi/pulumi";

// Blackbox exporter (synthetics, ADR-0011 Tier 3). Probes every tix HTTP service from outside
// the process — exactly as an external client would — and exposes `probe_*` series. A green probe
// means the whole ingress→service→handler path answers 2xx, which the in-process `up` self-scrape
// can't tell you (a process can be `up` while its HTTP surface is wedged). Unlike the k6 load
// generator this is ALWAYS on, in dev AND prod: synthetics are cheap and valuable everywhere, and
// outside-in liveness is the one signal that survives when the app's own telemetry degrades.
const BLACKBOX_IMAGE = "prom/blackbox-exporter:v0.27.0";

const HTTP_PORT = 9115;

export type BlackboxExporterArgs = { namespace: pulumi.Input<string> };

export class BlackboxExporter extends pulumi.ComponentResource {
  readonly config: k8s.core.v1.ConfigMap;
  readonly deployment: k8s.apps.v1.Deployment;
  readonly service: k8s.core.v1.Service;

  constructor(name: string, args: BlackboxExporterArgs, opts?: pulumi.ComponentResourceOptions) {
    super("tix:infra:BlackboxExporter", name, args, opts);

    const childOpts: pulumi.ResourceOptions = { parent: this };
    const { namespace } = args;

    const labels = {
      "app.kubernetes.io/name": "blackbox-exporter",
      "app.kubernetes.io/component": "observability",
    };

    this.config = new k8s.core.v1.ConfigMap(
      `${name}-config`,
      {
        metadata: { name: "blackbox-config", namespace },
        data: { "blackbox.yml": renderBlackboxConfig() },
      },
      childOpts,
    );

    this.deployment = new k8s.apps.v1.Deployment(
      `${name}-deployment`,
      {
        metadata: { name: "blackbox-exporter", namespace },
        spec: {
          replicas: 1,
          selector: { matchLabels: labels },
          template: {
            metadata: { labels },
            spec: {
              terminationGracePeriodSeconds: 30,
              containers: [
                {
                  name: "blackbox-exporter",
                  image: BLACKBOX_IMAGE,
                  args: ["--config.file=/etc/blackbox/blackbox.yml"],
                  ports: [{ name: "http", containerPort: HTTP_PORT }],
                  volumeMounts: [{ name: "config", mountPath: "/etc/blackbox", readOnly: true }],
                  readinessProbe: {
                    httpGet: { path: "/-/healthy", port: HTTP_PORT },
                    initialDelaySeconds: 5,
                    periodSeconds: 5,
                  },
                },
              ],
              volumes: [{ name: "config", configMap: { name: this.config.metadata.name } }],
            },
          },
        },
      },
      childOpts,
    );

    this.service = new k8s.core.v1.Service(
      `${name}-service`,
      {
        metadata: { name: "blackbox-exporter", namespace },
        spec: {
          selector: labels,
          ports: [{ name: "http", port: HTTP_PORT, targetPort: HTTP_PORT }],
        },
      },
      childOpts,
    );

    this.registerOutputs({
      config: this.config,
      deployment: this.deployment,
      service: this.service,
    });
  }
}

// Blackbox config: one `http_2xx` module the Prometheus `blackbox` job names via `module=[http_2xx]`.
// `preferred_ip_protocol: ip4` avoids the IPv6-first dial that times out in kind's v4-only network.
// Leaving `valid_status_codes` empty makes blackbox default to "2xx == success", which is what the
// services' /health and /ready endpoints return.
export function renderBlackboxConfig(): string {
  return `# Generated by tix:infra:BlackboxExporter (ADR-0011 Tier 3).
modules:
  http_2xx:
    prober: http
    timeout: 5s
    http:
      method: GET
      preferred_ip_protocol: ip4
      # valid_status_codes empty → blackbox defaults to 2xx = success.
`;
}
