import * as k8s from "@pulumi/kubernetes";
import * as pulumi from "@pulumi/pulumi";

// The Garage server image is a shell-less scratch image, so the bootstrap can't
// run the `garage` CLI in a script there. Instead this Job drives Garage's
// admin API (HTTP) with curl — `curlimages/curl` ships a busybox shell.
const CURL_IMAGE = "curlimages/curl:8.20.0";

export type GarageBucketsArgs = {
  namespace: pulumi.Input<string>;
  // Base URL of the Garage admin API, e.g. `http://garage:3903`.
  adminEndpoint: string;
  // Secret carrying GARAGE_ADMIN_TOKEN (bearer) + the S3 access key / secret to import.
  credentialsSecretName: pulumi.Input<string>;
  buckets: string[];
  keyName: string;
};

// Provisions Garage buckets and the S3 access key Tempo/Loki use, idempotently
// on every `pulumi up`. The Garage analogue of `StreamBootstrap`/`PostgresRoles`:
// a one-shot Job that waits for the node to report healthy, creates each bucket,
// imports the predetermined access key, and grants it read/write/owner via the
// admin API. Tempo and Loki `dependsOn` this so their buckets and credentials
// exist before they boot.
export class GarageBuckets extends pulumi.ComponentResource {
  readonly configMap: k8s.core.v1.ConfigMap;
  readonly job: k8s.batch.v1.Job;

  constructor(name: string, args: GarageBucketsArgs, opts?: pulumi.ComponentResourceOptions) {
    super("tix:infra:GarageBuckets", name, args, opts);

    const childOpts: pulumi.ResourceOptions = { parent: this };

    this.configMap = new k8s.core.v1.ConfigMap(
      `${name}-script`,
      {
        metadata: { name: `${name}-script`, namespace: args.namespace },
        data: {
          "garage-init.sh": renderInitScript(args.adminEndpoint, args.buckets, args.keyName),
        },
      },
      childOpts,
    );

    this.job = new k8s.batch.v1.Job(
      `${name}-job`,
      {
        metadata: { name, namespace: args.namespace },
        spec: {
          backoffLimit: 5,
          ttlSecondsAfterFinished: 600,
          template: {
            metadata: {
              labels: {
                "app.kubernetes.io/name": name,
                "app.kubernetes.io/component": "bootstrap",
              },
            },
            spec: {
              restartPolicy: "OnFailure",
              containers: [
                {
                  name: "garage-init",
                  image: CURL_IMAGE,
                  command: ["sh", "/script/garage-init.sh"],
                  envFrom: [{ secretRef: { name: args.credentialsSecretName } }],
                  volumeMounts: [{ name: "script", mountPath: "/script" }],
                },
              ],
              volumes: [{ name: "script", configMap: { name: this.configMap.metadata.name } }],
            },
          },
        },
      },
      childOpts,
    );

    this.registerOutputs({ configMap: this.configMap, job: this.job });
  }
}

// Generated bootstrap script, run by curl against the Garage admin API. Idempotent:
// CreateBucket / ImportKey tolerate an already-provisioned node (falling back to
// GetBucketInfo for the bucket id), and AllowBucketKey is a no-op when the grant
// already exists. Auth is the GARAGE_ADMIN_TOKEN bearer; the S3 key to import
// comes from GARAGE_S3_ACCESS_KEY / GARAGE_S3_SECRET_KEY.
function renderInitScript(adminEndpoint: string, buckets: string[], keyName: string): string {
  const perBucket = buckets
    .map(
      (b) => `
bucket_id="$(create_or_get_bucket ${b})"
if [ -z "$bucket_id" ]; then
  echo "garage-buckets: could not resolve id for bucket ${b}" >&2
  exit 1
fi
api AllowBucketKey "{\\"bucketId\\":\\"$bucket_id\\",\\"accessKeyId\\":\\"$GARAGE_S3_ACCESS_KEY\\",\\"permissions\\":{\\"read\\":true,\\"write\\":true,\\"owner\\":true}}" >/dev/null
echo "garage-buckets: granted ${keyName} on ${b} ($bucket_id)"`,
    )
    .join("\n");

  return `#!/bin/sh
# Generated by tix:infra:GarageBuckets. Idempotent. Drives the Garage admin API.
set -eu

ADMIN="${adminEndpoint}"
AUTH="Authorization: Bearer $GARAGE_ADMIN_TOKEN"

# POST helper: api <Endpoint> <json-body>
api() {
  curl -fsS -X POST "$ADMIN/v2/$1" -H "$AUTH" -H "Content-Type: application/json" -d "$2"
}

# Extract the first "id" field from a Garage JSON response. Garage pretty-prints
# JSON with whitespace after the colon, so the patterns tolerate it.
extract_id() {
  grep -oE '"id":[[:space:]]*"[^"]*"' | head -1 | sed -E 's/.*"([^"]+)"$/\\1/'
}

# Wait until the node reports healthy (single-node layout auto-applies on boot).
i=0
until curl -fsS "$ADMIN/v2/GetClusterHealth" -H "$AUTH" 2>/dev/null | grep -qE '"status":[[:space:]]*"healthy"'; do
  i=$((i + 1))
  if [ "$i" -ge 60 ]; then
    echo "garage-buckets: Garage not healthy after 60s" >&2
    exit 1
  fi
  sleep 1
done

# Import the predetermined S3 key (ignore "already exists" on reruns).
api ImportKey "{\\"accessKeyId\\":\\"$GARAGE_S3_ACCESS_KEY\\",\\"secretAccessKey\\":\\"$GARAGE_S3_SECRET_KEY\\",\\"name\\":\\"${keyName}\\"}" >/dev/null 2>&1 || true
echo "garage-buckets: key ${keyName} present"

# Create the bucket if absent, else look it up; echo its id.
create_or_get_bucket() {
  id="$(api CreateBucket "{\\"globalAlias\\":\\"$1\\"}" 2>/dev/null | extract_id)"
  if [ -z "$id" ]; then
    id="$(curl -fsS "$ADMIN/v2/GetBucketInfo?globalAlias=$1" -H "$AUTH" 2>/dev/null | extract_id)"
  fi
  echo "$id"
}
${perBucket}

echo "garage-buckets: ok"
`;
}
