import * as k8s from "@pulumi/kubernetes";
import * as pulumi from "@pulumi/pulumi";

import type { GarageBucketName } from "./garage-buckets.ts";

// Loki (logs), single-binary mode (`-target=all`, the default). Chunks + index
// land in Garage (S3). Config syntax targets Loki 3.x (tsdb / schema v13 / native
// OTLP ingest at /otlp/v1/logs).
const LOKI_IMAGE = "grafana/loki:3.7.2";

const HTTP_PORT = 3100;

export type LokiBackendArgs = {
  namespace: pulumi.Input<string>;
  s3Endpoint: string;
  bucket: GarageBucketName;
  credentialsSecretName: pulumi.Input<string>;
  // How long Loki keeps log streams before the compactor deletes them (Go
  // duration, e.g. `360h`). Without it logs accumulate in Garage forever.
  // Parameterized dev-small / prod-larger.
  retentionPeriod: string;
};

// Loki log backend. The gateway collector pushes logs over OTLP/HTTP to
// `/otlp/v1/logs`. S3 credentials come from the Garage Secret via env-var
// expansion (`-config.expand-env=true`), keeping them out of the ConfigMap.
// Storage of record is S3, so no PVC is needed.
export class LokiBackend extends pulumi.ComponentResource {
  readonly config: k8s.core.v1.ConfigMap;
  readonly deployment: k8s.apps.v1.Deployment;
  readonly service: k8s.core.v1.Service;

  constructor(name: string, args: LokiBackendArgs, opts?: pulumi.ComponentResourceOptions) {
    super("tix:infra:LokiBackend", name, args, opts);

    const childOpts: pulumi.ResourceOptions = { parent: this };
    const { namespace } = args;

    const labels = {
      "app.kubernetes.io/name": "loki",
      "app.kubernetes.io/component": "observability",
    };

    this.config = new k8s.core.v1.ConfigMap(
      `${name}-config`,
      {
        metadata: { name: "loki-config", namespace },
        data: {
          "loki.yaml": renderLokiConfig(args.s3Endpoint, args.bucket, args.retentionPeriod),
        },
      },
      childOpts,
    );

    this.deployment = new k8s.apps.v1.Deployment(
      `${name}-deployment`,
      {
        metadata: { name: "loki", namespace },
        spec: {
          replicas: 1,
          selector: { matchLabels: labels },
          template: {
            metadata: { labels },
            spec: {
              terminationGracePeriodSeconds: 30,
              containers: [
                {
                  name: "loki",
                  image: LOKI_IMAGE,
                  args: ["-config.file=/etc/loki/loki.yaml", "-config.expand-env=true"],
                  envFrom: [{ secretRef: { name: args.credentialsSecretName } }],
                  ports: [{ name: "http", containerPort: HTTP_PORT }],
                  volumeMounts: [{ name: "config", mountPath: "/etc/loki", readOnly: true }],
                  readinessProbe: {
                    httpGet: { path: "/ready", port: HTTP_PORT },
                    initialDelaySeconds: 15,
                    periodSeconds: 5,
                  },
                },
              ],
              volumes: [{ name: "config", configMap: { name: this.config.metadata.name } }],
            },
          },
        },
      },
      childOpts,
    );

    this.service = new k8s.core.v1.Service(
      `${name}-service`,
      {
        metadata: { name: "loki", namespace },
        spec: {
          selector: labels,
          ports: [{ name: "http", port: HTTP_PORT, targetPort: HTTP_PORT }],
        },
      },
      childOpts,
    );

    this.registerOutputs({
      config: this.config,
      deployment: this.deployment,
      service: this.service,
    });
  }
}

// Monolithic Loki config. `schema: v13` + `store: tsdb` + `object_store: s3` is
// the current (Loki 3.x) layout; `s3forcepathstyle` + `insecure` are mandatory
// for Garage and `region` must match Garage's `s3_region`.
// `allow_structured_metadata: true` is required for OTLP ingestion.
function renderLokiConfig(s3Endpoint: string, bucket: string, retentionPeriod: string): string {
  return `# Generated by tix:infra:LokiBackend (ADR-0009).
auth_enabled: false

server:
  http_listen_port: ${HTTP_PORT}

common:
  instance_addr: 127.0.0.1
  path_prefix: /loki
  replication_factor: 1
  ring:
    kvstore:
      store: inmemory
  storage:
    s3:
      endpoint: ${s3Endpoint}
      bucketnames: ${bucket}
      region: garage
      access_key_id: \${GARAGE_S3_ACCESS_KEY}
      secret_access_key: \${GARAGE_S3_SECRET_KEY}
      s3forcepathstyle: true
      insecure: true

schema_config:
  configs:
    - from: 2024-01-01
      store: tsdb
      object_store: s3
      schema: v13
      index:
        prefix: index_
        period: 24h

# Loki retention is enforced by the compactor, not storage TTLs: it must run with
# retention_enabled and a delete_request_store for the limits_config retention_period
# below to take effect, otherwise chunks pile up in Garage forever (ADR-0011 Tier 3).
compactor:
  working_directory: /loki/compactor
  retention_enabled: true
  delete_request_store: s3

limits_config:
  allow_structured_metadata: true
  retention_period: ${retentionPeriod}
`;
}
