import * as k8s from "@pulumi/kubernetes";
import * as pulumi from "@pulumi/pulumi";

// Gateway OTel Collector: the single OTLP ingress for the cluster. A thin
// receive-and-fan-out hop — core distro is enough (otlp receiver, batch
// processor, otlp + otlphttp exporters all ship in core).
const COLLECTOR_IMAGE = "otel/opentelemetry-collector:0.153.0";

const OTLP_GRPC_PORT = 4317;
const OTLP_HTTP_PORT = 4318;

const CONFIG_DIR = "/etc/otelcol";
const CONFIG_FILE = "config.yaml";

export type OtelCollectorArgs = {
  namespace: pulumi.Input<string>;
  // gRPC OTLP endpoint of the trace backend, bare host:port (e.g. `tempo:4317`).
  tempoEndpoint: string;
  // Full OTLP/HTTP logs URL of the log backend (e.g. `http://loki:3100/otlp/v1/logs`).
  lokiLogsEndpoint: string;
  // Full OTLP/HTTP metrics URL of the metrics backend
  // (e.g. `http://prometheus:9090/api/v1/otlp/v1/metrics`).
  prometheusMetricsEndpoint: string;
};

// The gateway collector. Apps export OTLP here (`otel-collector:4317` gRPC /
// `:4318` HTTP); it batches and fans out per signal: traces to Tempo (gRPC),
// logs to Loki (HTTP), metrics to Prometheus (HTTP).
export class OtelCollector extends pulumi.ComponentResource {
  readonly config: k8s.core.v1.ConfigMap;
  readonly deployment: k8s.apps.v1.Deployment;
  readonly service: k8s.core.v1.Service;

  constructor(name: string, args: OtelCollectorArgs, opts?: pulumi.ComponentResourceOptions) {
    super("tix:infra:OtelCollector", name, args, opts);

    const childOpts: pulumi.ResourceOptions = { parent: this };
    const { namespace } = args;

    const labels = {
      "app.kubernetes.io/name": "otel-collector",
      "app.kubernetes.io/component": "observability",
    };

    this.config = new k8s.core.v1.ConfigMap(
      `${name}-config`,
      {
        metadata: { name: "otel-collector-config", namespace },
        data: {
          [CONFIG_FILE]: renderCollectorConfig(
            args.tempoEndpoint,
            args.lokiLogsEndpoint,
            args.prometheusMetricsEndpoint,
          ),
        },
      },
      childOpts,
    );

    this.deployment = new k8s.apps.v1.Deployment(
      `${name}-deployment`,
      {
        metadata: { name: "otel-collector", namespace },
        spec: {
          replicas: 1,
          selector: { matchLabels: labels },
          template: {
            metadata: { labels },
            spec: {
              terminationGracePeriodSeconds: 30,
              containers: [
                {
                  name: "otel-collector",
                  image: COLLECTOR_IMAGE,
                  args: [`--config=${CONFIG_DIR}/${CONFIG_FILE}`],
                  ports: [
                    { name: "otlp-grpc", containerPort: OTLP_GRPC_PORT },
                    { name: "otlp-http", containerPort: OTLP_HTTP_PORT },
                  ],
                  volumeMounts: [{ name: "config", mountPath: CONFIG_DIR, readOnly: true }],
                },
              ],
              volumes: [{ name: "config", configMap: { name: this.config.metadata.name } }],
            },
          },
        },
      },
      childOpts,
    );

    this.service = new k8s.core.v1.Service(
      `${name}-service`,
      {
        metadata: { name: "otel-collector", namespace },
        spec: {
          selector: labels,
          ports: [
            { name: "otlp-grpc", port: OTLP_GRPC_PORT, targetPort: OTLP_GRPC_PORT },
            { name: "otlp-http", port: OTLP_HTTP_PORT, targetPort: OTLP_HTTP_PORT },
          ],
        },
      },
      childOpts,
    );

    this.registerOutputs({
      config: this.config,
      deployment: this.deployment,
      service: this.service,
    });
  }
}

// Receive OTLP (gRPC + HTTP), batch, fan out per signal. Tempo speaks OTLP gRPC
// (`otlp` exporter, `tls.insecure` for plaintext h2c); Loki and Prometheus speak
// OTLP/HTTP (`otlphttp` exporter with explicit per-signal endpoints to avoid
// path-suffix ambiguity). All three exporters are core-distro.
function renderCollectorConfig(
  tempoEndpoint: string,
  lokiLogsEndpoint: string,
  prometheusMetricsEndpoint: string,
): string {
  return `# Generated by tix:infra:OtelCollector. Gateway OTLP collector (ADR-0009).
receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:${OTLP_GRPC_PORT}
      http:
        endpoint: 0.0.0.0:${OTLP_HTTP_PORT}

processors:
  batch: {}

exporters:
  otlp/tempo:
    endpoint: ${tempoEndpoint}
    tls:
      insecure: true
  otlphttp/loki:
    logs_endpoint: ${lokiLogsEndpoint}
  otlphttp/prometheus:
    metrics_endpoint: ${prometheusMetricsEndpoint}

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp/tempo]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlphttp/loki]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlphttp/prometheus]
`;
}
