import * as k8s from "@pulumi/kubernetes";
import * as pulumi from "@pulumi/pulumi";

// Prometheus (metrics). Receives OTLP push directly (no scraping) and stores to
// a local TSDB on a PVC — vanilla Prometheus has no object-storage backend, so
// unlike Tempo/Loki it does not use Garage. Config/flags target Prometheus 3.x.
const PROMETHEUS_IMAGE = "prom/prometheus:v3.12.0";

const HTTP_PORT = 9090;

export type PrometheusBackendArgs = {
  namespace: pulumi.Input<string>;
  storage: string;
};

// Prometheus metrics backend. The gateway collector pushes OTLP metrics to
// `/api/v1/otlp/v1/metrics` (enabled by `--web.enable-otlp-receiver`). The
// out-of-order window is required: OTLP metrics routinely arrive late relative
// to the TSDB head and would otherwise be rejected and silently dropped.
export class PrometheusBackend extends pulumi.ComponentResource {
  readonly config: k8s.core.v1.ConfigMap;
  readonly statefulSet: k8s.apps.v1.StatefulSet;
  readonly service: k8s.core.v1.Service;

  constructor(name: string, args: PrometheusBackendArgs, opts?: pulumi.ComponentResourceOptions) {
    super("tix:infra:PrometheusBackend", name, args, opts);

    const childOpts: pulumi.ResourceOptions = { parent: this };
    const { namespace } = args;

    const labels = {
      "app.kubernetes.io/name": "prometheus",
      "app.kubernetes.io/component": "observability",
    };

    this.config = new k8s.core.v1.ConfigMap(
      `${name}-config`,
      {
        metadata: { name: "prometheus-config", namespace },
        data: { "prometheus.yml": renderPrometheusConfig() },
      },
      childOpts,
    );

    this.statefulSet = new k8s.apps.v1.StatefulSet(
      `${name}-set`,
      {
        metadata: { name: "prometheus", namespace },
        spec: {
          serviceName: "prometheus",
          replicas: 1,
          selector: { matchLabels: labels },
          template: {
            metadata: { labels },
            spec: {
              terminationGracePeriodSeconds: 30,
              containers: [
                {
                  name: "prometheus",
                  image: PROMETHEUS_IMAGE,
                  args: [
                    "--config.file=/etc/prometheus/prometheus.yml",
                    "--storage.tsdb.path=/prometheus",
                    "--web.enable-otlp-receiver",
                    "--web.enable-lifecycle",
                    // Store exemplars so the span-derived `duration` histograms
                    // (spanmetrics connector, ADR-0010) can drill to their trace.
                    // Grafana's Prometheus datasource maps the `trace_id` exemplar
                    // label to Tempo via `exemplarTraceIdDestinations`.
                    "--enable-feature=exemplar-storage",
                  ],
                  ports: [{ name: "http", containerPort: HTTP_PORT }],
                  volumeMounts: [
                    { name: "config", mountPath: "/etc/prometheus", readOnly: true },
                    { name: "data", mountPath: "/prometheus" },
                  ],
                  readinessProbe: {
                    httpGet: { path: "/-/ready", port: HTTP_PORT },
                    initialDelaySeconds: 5,
                    periodSeconds: 5,
                  },
                },
              ],
              volumes: [{ name: "config", configMap: { name: this.config.metadata.name } }],
            },
          },
          volumeClaimTemplates: [
            {
              metadata: { name: "data" },
              spec: {
                accessModes: ["ReadWriteOnce"],
                resources: { requests: { storage: args.storage } },
              },
            },
          ],
        },
      },
      childOpts,
    );

    this.service = new k8s.core.v1.Service(
      `${name}-service`,
      {
        metadata: { name: "prometheus", namespace },
        spec: {
          selector: labels,
          ports: [{ name: "http", port: HTTP_PORT, targetPort: HTTP_PORT }],
        },
      },
      childOpts,
    );

    this.registerOutputs({
      config: this.config,
      statefulSet: this.statefulSet,
      service: this.service,
    });
  }
}

// App telemetry arrives via OTLP push; `scrape_configs` adds static jobs for
// LGTM backend self-metrics (ADR-0010 Platform/o11y board). The job_name values
// match the `up{job=~"..."}` matcher the platform-o11y board uses.
// `out_of_order_time_window` accepts late OTLP samples; `promote_resource_attributes`
// lifts the OTel service identity onto the resulting series labels.
// Exported (not module-private) so unit tests can assert on the rendered config string
// without standing up the component; the ConfigMap consumes the same function.
export function renderPrometheusConfig(): string {
  return `# Generated by tix:infra:PrometheusBackend (ADR-0009; LGTM self-scrape ADR-0010).
global:
  scrape_interval: 30s

storage:
  tsdb:
    out_of_order_time_window: 30m

otlp:
  promote_resource_attributes:
    - service.namespace
    - service.name
    - service.instance.id

# App telemetry arrives via OTLP push; these scrape jobs add the LGTM backends' own
# self-metrics (ADR-0010 Platform/o11y board). The job_name values match the
# up{job=~"..."} matcher the platform-o11y board uses. Garage exposes /metrics on its
# admin port unauthenticated (no metrics_token set). The collector's internal telemetry
# is served on :8888 (see otel-collector.ts).
scrape_configs:
  - job_name: otel-collector
    static_configs:
      - targets: ["otel-collector:8888"]
  - job_name: tempo
    static_configs:
      - targets: ["tempo:3200"]
  - job_name: loki
    static_configs:
      - targets: ["loki:3100"]
  - job_name: prometheus
    static_configs:
      - targets: ["prometheus:9090"]
  - job_name: garage
    static_configs:
      - targets: ["garage:3903"]
`;
}
