import * as k8s from "@pulumi/kubernetes";
import * as pulumi from "@pulumi/pulumi";

import type { GarageBucketName } from "./garage-buckets.ts";

// Pyroscope (continuous profiling), monolithic single-binary mode (`-target=all`,
// the default). Profile blocks land in Garage (S3). Config syntax targets
// Pyroscope 1.x.
const PYROSCOPE_IMAGE = "grafana/pyroscope:1.14.0";

const HTTP_PORT = 4040;

export type PyroscopeBackendArgs = {
  namespace: pulumi.Input<string>;
  s3Endpoint: string;
  bucket: GarageBucketName;
  credentialsSecretName: pulumi.Input<string>;
  // How long Pyroscope keeps profile blocks in Garage before deleting them (Go
  // duration, e.g. `360h`). Without it the S3 bucket grows unbounded.
  // Parameterized dev-small / prod-larger (ADR-0011 Tier 3).
  retentionPeriod: string;
};

// Pyroscope profiling backend. Services push pprof profiles over HTTP to 4040;
// the same port serves the query API (Grafana's Pyroscope datasource reads it).
// S3 credentials come from the Garage Secret via env-var expansion
// (`-config.expand-env=true`), keeping them out of the ConfigMap. Storage of
// record is S3, so no PVC is needed (mirrors LokiBackend).
export class PyroscopeBackend extends pulumi.ComponentResource {
  readonly config: k8s.core.v1.ConfigMap;
  readonly deployment: k8s.apps.v1.Deployment;
  readonly service: k8s.core.v1.Service;

  constructor(name: string, args: PyroscopeBackendArgs, opts?: pulumi.ComponentResourceOptions) {
    super("tix:infra:PyroscopeBackend", name, args, opts);

    const childOpts: pulumi.ResourceOptions = { parent: this };
    const { namespace } = args;

    const labels = {
      "app.kubernetes.io/name": "pyroscope",
      "app.kubernetes.io/component": "observability",
    };

    this.config = new k8s.core.v1.ConfigMap(
      `${name}-config`,
      {
        metadata: { name: "pyroscope-config", namespace },
        data: {
          "pyroscope.yaml": renderPyroscopeConfig(
            args.s3Endpoint,
            args.bucket,
            args.retentionPeriod,
          ),
        },
      },
      childOpts,
    );

    this.deployment = new k8s.apps.v1.Deployment(
      `${name}-deployment`,
      {
        metadata: { name: "pyroscope", namespace },
        spec: {
          replicas: 1,
          selector: { matchLabels: labels },
          template: {
            metadata: { labels },
            spec: {
              terminationGracePeriodSeconds: 30,
              containers: [
                {
                  name: "pyroscope",
                  image: PYROSCOPE_IMAGE,
                  args: ["-config.file=/etc/pyroscope/pyroscope.yaml", "-config.expand-env=true"],
                  envFrom: [{ secretRef: { name: args.credentialsSecretName } }],
                  ports: [{ name: "http", containerPort: HTTP_PORT }],
                  volumeMounts: [{ name: "config", mountPath: "/etc/pyroscope", readOnly: true }],
                  readinessProbe: {
                    httpGet: { path: "/ready", port: HTTP_PORT },
                    initialDelaySeconds: 15,
                    periodSeconds: 5,
                  },
                },
              ],
              volumes: [{ name: "config", configMap: { name: this.config.metadata.name } }],
            },
          },
        },
      },
      childOpts,
    );

    this.service = new k8s.core.v1.Service(
      `${name}-service`,
      {
        metadata: { name: "pyroscope", namespace },
        spec: {
          selector: labels,
          ports: [{ name: "http", port: HTTP_PORT, targetPort: HTTP_PORT }],
        },
      },
      childOpts,
    );

    this.registerOutputs({
      config: this.config,
      deployment: this.deployment,
      service: this.service,
    });
  }
}

// Monolithic Pyroscope config. `storage.backend: s3` + the `s3:` sub-block is the
// Pyroscope 1.x layout; `force_path_style` + `insecure` are mandatory for Garage
// (path-style addressing, plaintext) and `region` must match Garage's `s3_region`.
// Retention is enforced by the compactor via `limits.compactor_blocks_retention_period`;
// without it the S3 bucket grows without bound (window is dev-small / prod-larger,
// ADR-0011 Tier 3).
//
// NOTE: version-sensitive keys for grafana/pyroscope:1.14.0 — confirm against
// the pinned image's config reference before bumping: `storage.backend`,
// `storage.s3.bucket_name`, `insecure`, `force_path_style`, and
// `limits.compactor_blocks_retention_period`. The kind smoke is the layer that
// proves Pyroscope actually boots and writes profile blocks to Garage.
function renderPyroscopeConfig(
  s3Endpoint: string,
  bucket: string,
  retentionPeriod: string,
): string {
  return `# Generated by tix:infra:PyroscopeBackend (ADR-0009).
server:
  http_listen_port: ${HTTP_PORT}

storage:
  backend: s3
  s3:
    endpoint: ${s3Endpoint}
    bucket_name: ${bucket}
    region: garage
    access_key_id: \${GARAGE_S3_ACCESS_KEY}
    secret_access_key: \${GARAGE_S3_SECRET_KEY}
    insecure: true
    force_path_style: true

# Profile blocks age out of Garage via the compactor; without a retention window
# the S3 bucket grows without bound (ADR-0011 Tier 3). The key is
# compactor_blocks_retention_period under limits; a bare limits.retention_period is
# not valid for grafana/pyroscope:1.14.0 (the server rejects it at config-validation).
limits:
  compactor_blocks_retention_period: ${retentionPeriod}
`;
}
