import * as k8s from "@pulumi/kubernetes";
import * as pulumi from "@pulumi/pulumi";

// Tempo (traces), monolithic single-binary mode. Blocks land in Garage (S3); the
// WAL + local cache live on a small PVC. Config syntax targets Tempo 3.x.
const TEMPO_IMAGE = "grafana/tempo:3.0.0";

const HTTP_PORT = 3200;
const OTLP_GRPC_PORT = 4317;

export type TempoBackendArgs = {
  namespace: pulumi.Input<string>;
  s3Endpoint: string;
  bucket: string;
  credentialsSecretName: pulumi.Input<string>;
  storage: string;
};

// Tempo trace backend. Receives OTLP directly from the gateway collector on
// 4317 and serves the search API on 3200 (the kind smoke polls it). S3
// credentials are read from the Garage Secret via env-var expansion
// (`-config.expand-env=true`), so they never land in the ConfigMap.
export class TempoBackend extends pulumi.ComponentResource {
  readonly config: k8s.core.v1.ConfigMap;
  readonly statefulSet: k8s.apps.v1.StatefulSet;
  readonly service: k8s.core.v1.Service;

  constructor(name: string, args: TempoBackendArgs, opts?: pulumi.ComponentResourceOptions) {
    super("tix:infra:TempoBackend", name, args, opts);

    const childOpts: pulumi.ResourceOptions = { parent: this };
    const { namespace } = args;

    const labels = {
      "app.kubernetes.io/name": "tempo",
      "app.kubernetes.io/component": "observability",
    };

    this.config = new k8s.core.v1.ConfigMap(
      `${name}-config`,
      {
        metadata: { name: "tempo-config", namespace },
        data: { "tempo.yaml": renderTempoConfig(args.s3Endpoint, args.bucket) },
      },
      childOpts,
    );

    this.statefulSet = new k8s.apps.v1.StatefulSet(
      `${name}-set`,
      {
        metadata: { name: "tempo", namespace },
        spec: {
          serviceName: "tempo",
          replicas: 1,
          selector: { matchLabels: labels },
          template: {
            metadata: { labels },
            spec: {
              terminationGracePeriodSeconds: 30,
              containers: [
                {
                  name: "tempo",
                  image: TEMPO_IMAGE,
                  args: ["-config.file=/etc/tempo/tempo.yaml", "-config.expand-env=true"],
                  envFrom: [{ secretRef: { name: args.credentialsSecretName } }],
                  ports: [
                    { name: "http", containerPort: HTTP_PORT },
                    { name: "otlp-grpc", containerPort: OTLP_GRPC_PORT },
                  ],
                  volumeMounts: [
                    { name: "config", mountPath: "/etc/tempo", readOnly: true },
                    { name: "data", mountPath: "/var/tempo" },
                  ],
                  readinessProbe: {
                    httpGet: { path: "/ready", port: HTTP_PORT },
                    initialDelaySeconds: 10,
                    periodSeconds: 5,
                  },
                },
              ],
              volumes: [{ name: "config", configMap: { name: this.config.metadata.name } }],
            },
          },
          volumeClaimTemplates: [
            {
              metadata: { name: "data" },
              spec: {
                accessModes: ["ReadWriteOnce"],
                resources: { requests: { storage: args.storage } },
              },
            },
          ],
        },
      },
      childOpts,
    );

    this.service = new k8s.core.v1.Service(
      `${name}-service`,
      {
        metadata: { name: "tempo", namespace },
        spec: {
          selector: labels,
          ports: [
            { name: "http", port: HTTP_PORT, targetPort: HTTP_PORT },
            { name: "otlp-grpc", port: OTLP_GRPC_PORT, targetPort: OTLP_GRPC_PORT },
          ],
        },
      },
      childOpts,
    );

    this.registerOutputs({
      config: this.config,
      statefulSet: this.statefulSet,
      service: this.service,
    });
  }
}

// Monolithic Tempo config. `forcepathstyle` + `insecure` are mandatory for
// Garage (path-style addressing, plaintext); `region` must match Garage's
// `s3_region` or sigv4 fails. The metrics_generator is omitted on purpose —
// ADR-0009 uses explicit `Effect.Metric` rather than span-derived metrics, so
// Tempo needs no Prometheus remote_write target.
function renderTempoConfig(s3Endpoint: string, bucket: string): string {
  return `# Generated by tix:infra:TempoBackend (ADR-0009).
server:
  http_listen_port: ${HTTP_PORT}

distributor:
  receivers:
    otlp:
      protocols:
        grpc:
          endpoint: 0.0.0.0:${OTLP_GRPC_PORT}

storage:
  trace:
    backend: s3
    s3:
      endpoint: ${s3Endpoint}
      bucket: ${bucket}
      region: garage
      access_key: \${GARAGE_S3_ACCESS_KEY}
      secret_key: \${GARAGE_S3_SECRET_KEY}
      insecure: true
      forcepathstyle: true
    wal:
      path: /var/tempo/wal
    local:
      path: /var/tempo/blocks
`;
}
